name: Deploy to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' # adjust version if needed

      - name: Build and publish
        run: |
          dotnet publish -c Release -o ./publish
        working-directory: ./CustomerSvc
      - name: Generate Swagger Documentation
        run: |
          dotnet swagger tofile --output ./swagger/index.html ./bin/Release/netcoreapp3.1/YourProject.dll
        working-directory: ./CustomerSvc

      - name: Copy Swagger UI to Output Directory
        run: |
          mkdir -p ./publish/swagger
          cp ./swagger/index.html ./publish/swagger
        working-directory: ./CustomerSvc
