name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: $(Build.ArtifactStagingDirectory) # Path to the published files
        target: '/path/to/iis/website' # Destination directory on the server

    - name: Configure IIS App Pool
      run: |
        # Commands to configure IIS application pool (if necessary)

    - name: Configure IIS Website
      run: |
        # Commands to configure IIS website (if necessary)

    - name: Configure Inbound Port
      run: |
        # Add inbound rule for port 105
        New-NetFirewallRule -DisplayName "Allow inbound port 105" -Direction Inbound -LocalPort 105 -Protocol TCP -Action Allow
