name: Deploy to IIS

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Adjust version as needed

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -o ./publish

    - name: Copy files to IIS directory
      run: xcopy /s /y .\publish\*.* C:\inetpub\wwwroot\YourApp\

    # Optionally, restart IIS
    # - name: Restart IIS
    #   run: iisreset /restart
