name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)

    - name: Deploy to IIS
      uses: warrenbuckley/DeployIISWebsite@1.0.1
      with:
        WebsiteName: 'MyDotNetApp'
        PhysicalPath: '$(Build.ArtifactStagingDirectory)'
        AppPoolName: 'MyAppPool'

    - name: Configure Inbound Port
      run: |
        # Add inbound rule for port 105
        New-NetFirewallRule -DisplayName "Allow inbound port 105" -Direction Inbound -LocalPort 105 -Protocol TCP -Action Allow
